/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/app'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthSigninRouteImport } from './routes/_auth.signin'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicHowItWorksRouteImport } from './routes/_public/how-it-works'
import { Route as PublicLegalRouteImport } from './routes/_public/legal'
import { Route as PublicTransparencyRouteImport } from './routes/_public/transparency'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAddFarmRouteImport } from './routes/app/add-farm'
import { Route as PublicProductsIndexRouteImport } from './routes/_public/products/index'
import { Route as PublicProductsProductIdRouteImport } from './routes/_public/products/$productId'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as AppDocumentsIndexRouteImport } from './routes/app/documents/index'
import { Route as AppMonitoringIndexRouteImport } from './routes/app/monitoring/index'
import { Route as AppNotificationsIndexRouteImport } from './routes/app/notifications/index'
import { Route as AppPayoutsIndexRouteImport } from './routes/app/payouts/index'
import { Route as AppPlannerIndexRouteImport } from './routes/app/planner/index'
import { Route as AppProtectionIndexRouteImport } from './routes/app/protection/index'
import { Route as AppProtectionProductIdRouteImport } from './routes/app/protection/$productId'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppSupportIndexRouteImport } from './routes/app/support/index'
import { Route as AppWalletIndexRouteImport } from './routes/app/wallet/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHowItWorksRoute = PublicHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLegalRoute = PublicLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTransparencyRoute = PublicTransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => PublicRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAddFarmRoute = AppAddFarmRouteImport.update({
  id: '/add-farm',
  path: '/add-farm',
  getParentRoute: () => AppRoute,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsProductIdRoute = PublicProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => PublicRoute,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringIndexRoute = AppMonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayoutsIndexRoute = AppPayoutsIndexRouteImport.update({
  id: '/payouts/',
  path: '/payouts/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerIndexRoute = AppPlannerIndexRouteImport.update({
  id: '/planner/',
  path: '/planner/',
  getParentRoute: () => AppRoute,
} as any)
const AppProtectionIndexRoute = AppProtectionIndexRouteImport.update({
  id: '/protection/',
  path: '/protection/',
  getParentRoute: () => AppRoute,
} as any)
const AppProtectionProductIdRoute = AppProtectionProductIdRouteImport.update({
  id: '/protection/$productId',
  path: '/protection/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportIndexRoute = AppSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletIndexRoute = AppWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/how-it-works': typeof PublicHowItWorksRoute
  '/legal': typeof PublicLegalRoute
  '/transparency': typeof PublicTransparencyRoute
  '/app/add-farm': typeof AppAddFarmRoute
  '/app/': typeof AppIndexRoute
  '/products/$productId': typeof PublicProductsProductIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/app/protection/$productId': typeof AppProtectionProductIdRoute
  '/products/': typeof PublicProductsIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/monitoring/': typeof AppMonitoringIndexRoute
  '/app/notifications/': typeof AppNotificationsIndexRoute
  '/app/payouts/': typeof AppPayoutsIndexRoute
  '/app/planner/': typeof AppPlannerIndexRoute
  '/app/protection/': typeof AppProtectionIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/support/': typeof AppSupportIndexRoute
  '/app/wallet/': typeof AppWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/how-it-works': typeof PublicHowItWorksRoute
  '/legal': typeof PublicLegalRoute
  '/transparency': typeof PublicTransparencyRoute
  '/app/add-farm': typeof AppAddFarmRoute
  '/app': typeof AppIndexRoute
  '/products/$productId': typeof PublicProductsProductIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/app/protection/$productId': typeof AppProtectionProductIdRoute
  '/products': typeof PublicProductsIndexRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/monitoring': typeof AppMonitoringIndexRoute
  '/app/notifications': typeof AppNotificationsIndexRoute
  '/app/payouts': typeof AppPayoutsIndexRoute
  '/app/planner': typeof AppPlannerIndexRoute
  '/app/protection': typeof AppProtectionIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/support': typeof AppSupportIndexRoute
  '/app/wallet': typeof AppWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/how-it-works': typeof PublicHowItWorksRoute
  '/_public/legal': typeof PublicLegalRoute
  '/_public/transparency': typeof PublicTransparencyRoute
  '/app/add-farm': typeof AppAddFarmRoute
  '/_public/': typeof PublicIndexRoute
  '/app/': typeof AppIndexRoute
  '/_public/products/$productId': typeof PublicProductsProductIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/app/protection/$productId': typeof AppProtectionProductIdRoute
  '/_public/products/': typeof PublicProductsIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/monitoring/': typeof AppMonitoringIndexRoute
  '/app/notifications/': typeof AppNotificationsIndexRoute
  '/app/payouts/': typeof AppPayoutsIndexRoute
  '/app/planner/': typeof AppPlannerIndexRoute
  '/app/protection/': typeof AppProtectionIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/support/': typeof AppSupportIndexRoute
  '/app/wallet/': typeof AppWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sitemap.xml'
    | '/signin'
    | '/signup'
    | '/about'
    | '/contact'
    | '/how-it-works'
    | '/legal'
    | '/transparency'
    | '/app/add-farm'
    | '/app/'
    | '/products/$productId'
    | '/api/public/contact'
    | '/app/protection/$productId'
    | '/products/'
    | '/app/documents/'
    | '/app/monitoring/'
    | '/app/notifications/'
    | '/app/payouts/'
    | '/app/planner/'
    | '/app/protection/'
    | '/app/settings/'
    | '/app/support/'
    | '/app/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/signin'
    | '/signup'
    | '/about'
    | '/contact'
    | '/how-it-works'
    | '/legal'
    | '/transparency'
    | '/app/add-farm'
    | '/app'
    | '/products/$productId'
    | '/api/public/contact'
    | '/app/protection/$productId'
    | '/products'
    | '/app/documents'
    | '/app/monitoring'
    | '/app/notifications'
    | '/app/payouts'
    | '/app/planner'
    | '/app/protection'
    | '/app/settings'
    | '/app/support'
    | '/app/wallet'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/app'
    | '/sitemap.xml'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/how-it-works'
    | '/_public/legal'
    | '/_public/transparency'
    | '/app/add-farm'
    | '/_public/'
    | '/app/'
    | '/_public/products/$productId'
    | '/api/public/contact'
    | '/app/protection/$productId'
    | '/_public/products/'
    | '/app/documents/'
    | '/app/monitoring/'
    | '/app/notifications/'
    | '/app/payouts/'
    | '/app/planner/'
    | '/app/protection/'
    | '/app/settings/'
    | '/app/support/'
    | '/app/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/how-it-works': {
      id: '/_public/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof PublicHowItWorksRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/legal': {
      id: '/_public/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof PublicLegalRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/transparency': {
      id: '/_public/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof PublicTransparencyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/add-farm': {
      id: '/app/add-farm'
      path: '/add-farm'
      fullPath: '/app/add-farm'
      preLoaderRoute: typeof AppAddFarmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products/$productId': {
      id: '/_public/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof PublicProductsProductIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/documents'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoring/': {
      id: '/app/monitoring/'
      path: '/monitoring'
      fullPath: '/app/monitoring/'
      preLoaderRoute: typeof AppMonitoringIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications/': {
      id: '/app/notifications/'
      path: '/notifications'
      fullPath: '/app/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payouts/': {
      id: '/app/payouts/'
      path: '/payouts'
      fullPath: '/app/payouts/'
      preLoaderRoute: typeof AppPayoutsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planner/': {
      id: '/app/planner/'
      path: '/planner'
      fullPath: '/app/planner/'
      preLoaderRoute: typeof AppPlannerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/protection/': {
      id: '/app/protection/'
      path: '/protection'
      fullPath: '/app/protection/'
      preLoaderRoute: typeof AppProtectionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/protection/$productId': {
      id: '/app/protection/$productId'
      path: '/protection/$productId'
      fullPath: '/app/protection/$productId'
      preLoaderRoute: typeof AppProtectionProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support/': {
      id: '/app/support/'
      path: '/support'
      fullPath: '/app/support/'
      preLoaderRoute: typeof AppSupportIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/': {
      id: '/app/wallet/'
      path: '/wallet'
      fullPath: '/app/wallet/'
      preLoaderRoute: typeof AppWalletIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicHowItWorksRoute: typeof PublicHowItWorksRoute
  PublicLegalRoute: typeof PublicLegalRoute
  PublicTransparencyRoute: typeof PublicTransparencyRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicProductsProductIdRoute: typeof PublicProductsProductIdRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicHowItWorksRoute: PublicHowItWorksRoute,
  PublicLegalRoute: PublicLegalRoute,
  PublicTransparencyRoute: PublicTransparencyRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicProductsProductIdRoute: PublicProductsProductIdRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AppRouteChildren {
  AppAddFarmRoute: typeof AppAddFarmRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProtectionProductIdRoute: typeof AppProtectionProductIdRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppMonitoringIndexRoute: typeof AppMonitoringIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
  AppPayoutsIndexRoute: typeof AppPayoutsIndexRoute
  AppPlannerIndexRoute: typeof AppPlannerIndexRoute
  AppProtectionIndexRoute: typeof AppProtectionIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSupportIndexRoute: typeof AppSupportIndexRoute
  AppWalletIndexRoute: typeof AppWalletIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddFarmRoute: AppAddFarmRoute,
  AppIndexRoute: AppIndexRoute,
  AppProtectionProductIdRoute: AppProtectionProductIdRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppMonitoringIndexRoute: AppMonitoringIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
  AppPayoutsIndexRoute: AppPayoutsIndexRoute,
  AppPlannerIndexRoute: AppPlannerIndexRoute,
  AppProtectionIndexRoute: AppProtectionIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSupportIndexRoute: AppSupportIndexRoute,
  AppWalletIndexRoute: AppWalletIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
